name: TestEvol
nbPart: 10
nbRand: 10000
TFs:
    Schmidt12: CTCF
    Myers: CTCF
    Schmidt10: CEBPA
    Rensch: CEBPA
    Wilson:
        - CEBPA
        - HNF4A
        - FOXA1
        - HNF6
    Stefflova:
        - CEBPA
        - HNF4A
        - FOXA1
cluster:
    path: "/work/FAC/FBM/DEE/mrobinso/evolseq/DetectPosSel"
    split: "split"
    localrules: all, GetPeaks, BED_split, ConcatSeq, ConsensusSummits
local:
    path: "/Users/alaverre/Documents/Detecting_positive_selection"
    split: "gsplit"
    localrules: all, GetPeaks, GenerateNegativeSeq,ModelTraining,ModelValidation,ModelPrediction, BED_split,
        InferAncestralPairwise,GetSequencesMultiple,ConcatSeq,TestPosSel, ArchiveAlignments, ConsensusSummits





