name: TestEvol
nbPart: 10
nbRand: 10000
nbBin: 50
AlignType: 'MAF'
AncMethod: 'parsimony'
peakType: 'NarrowPeaks'
TFs:
    Schmidt12: ['CTCF']
    Myers: ['CTCF']
    Schmidt10: ['CEBPA']
    Rensch: ['CEBPA']
    Kern: ['CTCF']
    Wilson:
        - 'CEBPA'
        - 'HNF4A'
        - 'FOXA1'
        - 'HNF6'
    Stefflova:
        - 'CEBPA'
        - 'HNF4A'
        - 'FOXA1'
human:
    UCSC_Assembly: 'hg38.fa.gz'
    Ensembl_Assembly: 'Homo_sapiens.GRCh38.dna_sm.toplevel.fa.gz'
    suffix: '_UCSC_names'
    sample:
        - 'Wilson'
        - 'Schmidt12'
mouse:
    UCSC_Assembly: 'mm10.fa.gz'
    Ensembl_Assembly: 'Mus_musculus.GRCm38.dna_sm.toplevel.fa.gz'
    suffix: '_UCSC_names'
    sample:
        - 'Wilson'
        - 'Schmidt12'
caroli:
    UCSC_Assembly: 'GCA_900094665.2_CAROLI_EIJ_v1.1.fa.gz'
    Ensembl_Assembly: 'Mus_caroli.CAROLI_EIJ_v1.1.dna_sm.toplevel.fa.gz'
    suffix: '_UCSC_names'
    sample: ['Stefflova']
spretus:
    UCSC_Assembly: 'GCA_001624865.1_SPRET_EiJ_v1.fa.gz'
    Ensembl_Assembly: 'Mus_spretus.SPRET_EiJ_v1.dna_sm.toplevel.fa.gz'
    suffix: '_UCSC_names'
    sample: ['Stefflova']
rat:
    UCSC_Assembly: 'rn6.fa.gz'
    Ensembl_Assembly: 'Rattus_norvegicus.Rnor_6.0.dna_sm.toplevel.fa.gz'
    suffix: '_UCSC_names'
    sample:
        - 'Wilson'
        - 'Schmidt12'
macaca:
    UCSC_Assembly: 'rheMac8.fa.gz'
    Ensembl_Assembly: 'sup2kb_GCA_000772875.3_Mmul_8.0.1_genomic.fna.gz'
    suffix: '_UCSC_names'
    sample:
        - 'Wilson'
        - 'Schmidt12'
dog:
    UCSC_Assembly: 'canFam3.fa.gz'
    Ensembl_Assembly: 'Canis_lupus_familiaris.CanFam3.1.dna_sm.toplevel.fa.gz'
    suffix: ''
    sample: ['Wilson', 'Rensch', 'Schmidt12']
rabbit:
    UCSC_Assembly: 'oryCun2.fa.gz'
    Ensembl_Assembly: 'Oryctolagus_cuniculus.OryCun2.0.dna_sm.toplevel.fa.gz'
    suffix: ''
chicken:
    UCSC_Assembly: 'galGal6.fa.gz'
    Ensembl_Assembly: 'Gallus_gallus.GRCg6a.dna_sm.toplevel.fa.gz'
    suffix: ''
    sample: ['Schmidt10']
cat:
    UCSC_Assembly: 'felCat8.fa.gz'
    Ensembl_Assembly: 'sup2kb_GCA_000181335.3_Felis_catus_8.0_genomic.fna.gz'
    suffix: ''
    sample: ['Schmidt10', 'Rensch']
split:
    cluster: 'split'
    local: 'gsplit'






